version: '3'
services:

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    ports:
      - 9200:9200
      - 9300:9300

  python_app:
    build: .
    ports:
      - 5000:5000
    container_name: app
    depends_on:
      - es